

service: little-bunny # NOTE: update this with your service name


provider:
  name: aws
  memorySize: 128
  runtime: nodejs6.10
functions:
  register:
    handler: handler.register
    events:
     - http:
         path: users/register
         method: post
